// <auto-generated />
using FlightBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBooking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    partial class FlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightBooking.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            Code = "IST",
                            Name = "İstanbul Havalimanı"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ankara",
                            Code = "ESB",
                            Name = "Esenboğa Havalimanı"
                        },
                        new
                        {
                            Id = 3,
                            City = "London",
                            Code = "LHR",
                            Name = "London Heathrow"
                        },
                        new
                        {
                            Id = 4,
                            City = "Antalya",
                            Code = "AYT",
                            Name = "Antalya Havalimanı"
                        },
                        new
                        {
                            Id = 5,
                            City = "İzmir",
                            Code = "IZM",
                            Name = "İzmir Alsancak Havalimanı"
                        },
                        new
                        {
                            Id = 6,
                            City = "Gaziantep",
                            Code = "GZT",
                            Name = "Gaziantep Havalimanı"
                        },
                        new
                        {
                            Id = 7,
                            City = "Kayseri",
                            Code = "KYA",
                            Name = "Kayseri Havalimanı"
                        },
                        new
                        {
                            Id = 8,
                            City = "Adana",
                            Code = "GNY",
                            Name = "Adana Havalimanı"
                        },
                        new
                        {
                            Id = 9,
                            City = "İstanbul",
                            Code = "SAW",
                            Name = "Sabiha Gökçen Havalimanı"
                        },
                        new
                        {
                            Id = 10,
                            City = "Muğla",
                            Code = "DLM",
                            Name = "Dalaman Havalimanı"
                        },
                        new
                        {
                            Id = 11,
                            City = "New York",
                            Code = "NYC",
                            Name = "John F. Kennedy Airport"
                        },
                        new
                        {
                            Id = 12,
                            City = "Los Angeles",
                            Code = "LAX",
                            Name = "Los Angeles International"
                        },
                        new
                        {
                            Id = 13,
                            City = "Paris",
                            Code = "CDG",
                            Name = "Paris Charles de Gaulle"
                        },
                        new
                        {
                            Id = 14,
                            City = "Amsterdam",
                            Code = "AMS",
                            Name = "Amsterdam Schiphol"
                        },
                        new
                        {
                            Id = 15,
                            City = "Dubai",
                            Code = "DXB",
                            Name = "Dubai International"
                        },
                        new
                        {
                            Id = 16,
                            City = "Tokyo",
                            Code = "NRT",
                            Name = "Narita International"
                        },
                        new
                        {
                            Id = 17,
                            City = "Sydney",
                            Code = "SYD",
                            Name = "Sydney Airport"
                        },
                        new
                        {
                            Id = 18,
                            City = "Singapore",
                            Code = "SIN",
                            Name = "Singapore Changi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
